git:
  submodules: false # the submodules are just for demo and are loaded via url

language: node_js

node_js:
  - stable

install:
  - npm install
  - npm run install:examples

script:
  - npm run test

after_success:
  - npm run build:all

deploy:
  local_dir: examples/dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
